---
title: "Data Visualization"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=F, warning=F}

# Load libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(RColorBrewer)
library(scales)

```

# Reformat data for plotting

[Alaska Department of Fish and Game, Division of Commercial Fisheries. 2017. Daily salmon escapement counts from he OceanAK database, Alaska, 1921-2017. Knowledge Network for Biocomplexity. doi:10.5063/F1S46Q6M.](https://knb.ecoinformatics.org/view/doi:10.5063/F1S46Q6M) 

```{r}

esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", method="libcurl"), stringsAsFactors=FALSE)

```

* Calculate annual escapement by species and region 
    + `separate`
    + `group_by`
    + `summarize` using `sum` function
* Filter for just Pacific salmon species (Sockeye, Chinook, Coho, Pink, Chum)
    + `filter` 

```{r}

annual_esc <- esc %>% 
  separate(sampleDate, c("Year","Month","Day"), "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(SASAP.Region, Species, Year) %>% 
  summarize(Count = sum(DailyCount)) %>% 
  filter(Species %in% c("Sockeye", "Chinook", "Coho", "Pink", "Chum"))
  
```


# Generate some static plots 

Save theme function calls to an object.

```{r, echo=F}
my_theme <- theme_test() + 
  theme(legend.position = "bottom", legend.title=element_blank(), plot.title=element_text(hjust = 0.5))
```


```{r, echo=F}

ggplot(annual_esc, aes(x=Species, y=Count, fill=SASAP.Region)) + 
  #scale_fill_brewer(palette = "Dark2")
  geom_col()

```

```{r, echo=F}
ggplot(filter(annual_esc,SASAP.Region == "Kodiak"), 
       aes(x=Year, y=Count, color=Species)) + 
  geom_line() + 
  geom_point() + 
  scale_y_continuous(labels = comma) +
  ylab("Escapement (Number of fish)") + 
  xlab("Year") +
  ggtitle("Kodiak Salmon Escapement") + 
  my_theme

```

Create plots for all of the regions. 

```{r, fig.width = 7, fig.height = 8, echo=F}

p <- ggplot(annual_esc, aes(x=Year, y=Count, color=Species)) +
  geom_line() +
  geom_point() + 
  scale_y_continuous(label = comma) + 
  facet_wrap(~SASAP.Region, scales="free_y", ncol=2) + 
  my_theme

p
  
# ggsave("figures/regional_escapement.png", plot = p)

```


# Create an interactive map 

